# Setup
title:        Chen's Blog
tagline:      Keep coding and carry on!
baseurl:      ""
paginate:     10

# About/contact
author:
  name:       Chen Chen
  url:        http://github.com/exiachen
  email:      exiachen@hotmail.com
  github:     http://github.com/exiachen

# Gems
gems:
  - jekyll-paginate

#Others
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: 
    - fenced_code_blocks
    - no_intra_emphasis
    - strikethrough
    - autolink
    - tables
